### ISSUE TITLE
font size in Bible entry

### ISSUE THREAD

**Issue by upossekel** [srophe/e-gedsh#108]
The font size in the comment just before bibliography seems too large.

http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/entry.html?id=http://gedsh.bethmardutho.org/Bible-General

In XML it is marked as 'head' but it should just be formatted as normal text. Line 12156.

**Comment by dlschwartz** [comment]
@upossekel, this is an encoding issue. All head elements under listBibls are set up to have a larger font size. We regularly see this with the "Primary Sources" and "Secondary Sources" text in the bibl. We can approach this one of two ways, we can make a universal change so that all head elements nested under listBibl elements appear the same, or we have to find those things encoded under a listBibl element that we want to appear in the same font as the regular text, and encode them differently. The latter is a bit more work, but I think that better reflects what we see in the print edition (this sentence does not appear in a larger font in the print edition whereas "Primary Sources" and "Secondary Sources" do appear in a larger font). You can use Xpath in a find all search to help narrow things down. Please let me know if you would prefer me to make this fix. I'm happy to do so. Thanks Ute.

**Comment by wsalesky** [comment]
@dlschwartz Has this been resolved?

**Comment by dlschwartz** [comment]
Yes, thank you!
