### ISSUE TITLE
superscript in italicized font

### ISSUE THREAD

**Issue by upossekel** [srophe/e-gedsh#124]
In the bibliographies there occur titles with superscript. Although formatted correctly in XML, these appear in the html as if there were a space before the superscript. Can this be adjusted?

Example: XLM line 41052 and following.
Bibliographic entry for Beauchamp in entry on Nagran.
http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/entry.html?id=http://gedsh.bethmardutho.org/Nagran&fq=;fq-Browse:N;fq-Browse:N

**Comment by dlschwartz** [comment]
@wsalesky I think we need your help on this one.  There are two examples of superscripted letters in this Nagran entry that appear to have additional space preceding them (it also shows up as a superscripted space when I cut and paste into Word). However, there is one example in this entry where a superscripted number does not show this space. However, fixing this can probably wait until after the workshop since it is a lower priority. Thanks!

**Comment by wsalesky** [comment]
I will take a look this weekend.

**Comment by upossekel** [comment]
Have you got a chance to look at this yet? It would be super helpful if that were fixed. (I wonder if the problem is similar to the one we had some time ago with the 'abbrev.' element that would always cause extra spaces to appear. Thanks!

**Comment by wsalesky** [comment]
I will try to get to it tomorrow.
