### ISSUE TITLE
is there unicode character for j with line below?

### ISSUE THREAD

**Issue by upossekel** [srophe/e-gedsh#125]
needed for title of Shahid, in entry on Nagran.
XML line 41073.

**Comment by dlschwartz** [comment]
@upossekel I'm not great with Arabic transliteration but g, j, and dj are frequently used for this letter. I cannot find a dj underlined ligature in unicode which is what this should since it represents a single letter in Arabic. Have you tried to track down what is actually in EI. I'm embarrassed to say that I can't get access through our library here. If Shahid actually has dj with a line, that would be a bit odd. For example, the entries that Brill let's you preview without a subscription do not show this spelling for Nagran. If the original article actually has this spelling, we should ask George about unicode but I'm guessing the solution will simply be to use the English letters and underline them with a hi rend="underline". Please try to track down Shahid's article and if that's what it has, we'll go from there. Thanks.

**Comment by dlschwartz** [comment]
@upossekel Had you already solved this? There is a line. It's hard to see in the xml but it's there. Look here: http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/Nagran/tei. (You may need to use ctrl+"+" to enlarge the font.) I would prefer to have a ligature for this, but if Shahid has a d with line and j with line, I think what we have now is just fine.

**Comment by upossekel** [comment]
Yes, I checked. in Enc. Isl. it had dj underlined. The line should not be broken up for each letter. There must be a way to represent this. Can someone please ask their Arabic-specialist colleagues?

**Comment by nathangibson** [comment]
I'm not finding a unicode character for this either, but what about using a "combining low line" (U+0332) e.g., "d̲j̲" or "combining double macron below" (U+035F) e.g., "d͟j"?

**Comment by nathangibson** [comment]
For what it's worth, Brill's online version of EI2 uses "combining low line", e.g., "Nad̲j̲rān" but somehow makes it look as if it's a single line. (http://referenceworks.brillonline.com/entries/encyclopaedia-of-islam-2/nadjran-SIM_5729)
<img width="87" alt="nad j ran_-_brill_reference" src="https://cloud.githubusercontent.com/assets/3083452/26645678/f1b140f0-4606-11e7-967f-ffbbf1405217.png">

Probably they have this rendering written into their special "Brill" font -- I don't see any special CSS rules but you could have Winona check it out if it's important. 

However, according to this Wikipedia page (https://en.wikipedia.org/wiki/Macron_below) I would guess that the combining double macron below is more correct. The page is rather confusing though. 

Upshot is that you can probably use whichever one appears correctly on the page rather than worrying about which one is the "correct" unicode.

**Comment by dlschwartz** [comment]
I've used d͟j̱ (U+0064 U+035F U+006A). It looks awful in text mode in oxygen but looks good in author mode. I'm hoping it renders well into HTML. Web hooks seem to be down at the moment though so I'll have to test later.

**Comment by dlschwartz** [comment]
By the way, many thanks @nathangibson!
