### ISSUE TITLE
title with italics and non-italics

### ISSUE THREAD

**Issue by upossekel** [srophe/e-gedsh#132]
The last bibliographic item for 'Tatian' has a title that is only partially italicized.
http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/entry.html?id=http://gedsh.bethmardutho.org/Tatian&num=534

The XML needed to be fixed to reflect this, and I tried to separate the 'italics' function from the title, using 'hi=' instead of 'rend='. The result, as can be seen, was not satisfactory. While the italics are in the right spots, the entire title now is underlined. The same XML coding, however, did seem to work in other places.

XML line 53988.

**Comment by dlschwartz** [comment]
@wsalesky I think we need your help on this one. The problem has to do with a title inside of a title. Since the inset title would normally be italicized it returns to a regular font when put inside of an italicized title. It looks like the CSS has default underline for titles without attributes. The whole title is underlined after Ute tried to address the problem by doing the following:

`<bibl>M. Whittaker, <title><hi rend="italic">Tatian: </hi>Oratio ad Graecos<hi rend="italic"> and fragments</hi> </title> (1982). (with <abbr>ET</abbr>)</bibl>`

It seems the options are for you to tweak the CSS or Ute to tweak the TEI. Which would be preferable?

By the way, there are no other title elements without the attribute rend="italic" anywhere in e-GEDSH. 

Thanks.

**Comment by wsalesky** [comment]
I will adjust the css. I'm working on something else today, but will try to get to it tonight.

**Comment by dlschwartz** [comment]
Thanks @wsalesky! This is fairly low priority.

**Comment by wsalesky** [comment]
@upossekel 
The webhook was complaining about malformed xml, however I did not see any when I opened the latest version. I re-ran the most recent webhook and it seemed to work (no errors in from the webhook). Please check and let me know if you see your changes. Also, can you let me know the next time you push to github, so I can monitor this issue? 
I will be available until 5 EST and then after 8:30 EST.

**Comment by upossekel** [comment]
All set, thank you! Changes are visible and I could sync with no problem. It seems that the earlier error cause the problem, sorry for overlooking the malformed code.

**Comment by wsalesky** [comment]
Great, I will try to be available over the next few days in case you run
into any additional problems.

**Comment by wsalesky** [comment]
@upossekel @dlschwartz 
I think this has been resolved. Please reopen if not.

**Comment by dlschwartz** [comment]
Looks great, thanks.
