### ISSUE TITLE
curved single quotes

### ISSUE THREAD

**Issue by upossekel** [srophe/e-gedsh#135]
How does one insert curved single (or double, for that matter) quotes into Oxygen? We've talked about it before, but could not resolve it. In body text it was fine to copy and past, but in the captions this is a frequent error in the XML and copy/paste would be rather laborious.

**Comment by wsalesky** [comment]
@dlschwartz Do you know? This is not something I generally do.

**Comment by upossekel** [comment]
I decided to copy and past, to get on with it. So we can close this issue, though in general this would be a good thing to know.

**Comment by dlschwartz** [comment]
I'm sorry about the delay here. You can set up oxygen to put in smart quotes (like Word does) but you have to be in Author mode which is kind of a hassle. Oxygen does includes this restriction is because you need straight quotes wrapping attribute values. What you want to do is a find all and replace. But when you do that you need to select "Enable XML search options" and then select "element contents". That way you will only change quotes in the text nodes. You will need to do this four times for open and close, single and double. Let me know if there are any questions.

**Comment by dlschwartz** [comment]
@upossekel I just found an additional three "straight" apostrophes and changed them to "smart". You will need to pull in order to have these in your copy. I believe this should finish all of the smart quote issues so I'll close this comment.
