### ISSUE TITLE
how would be format XML to center headlines?

### ISSUE THREAD

**Issue by upossekel** [srophe/e-gedsh#155]
This applies to various titles and subtitles in front and back matter.

**Comment by dlschwartz** [comment]
@upossekel I'll take this one as well. Just as each entry get's it's own page in html, we will likely want to break this material down into separate pages. In part, this will likely mean tweaking some of the encoding and in part this will require some changes to the app. Let me look at this and decide how best to proceed. Thanks.

**Comment by upossekel** [comment]
Yes, the whole subject of front and back matter will need some consideration. What I wanted to do just now is format it in agreement with print version. A simple attribute for centering text would do. But we can also leave it for later.

**Comment by dlschwartz** [comment]
@upossekel Take a look at the Table of Contents on page v of the print edition. If you extract the Entries A-Z, I would like to think of each of these things as the structural equivalent of a headword. So, rather than having a page containing many, many screens worth of text as we currently have, these would each be broken out to have its own page. Links will allow users to navigate to these pages. I'm not yet sure how (or whether?) to integrate these links into the alphabetical list of terms that reside in the left margin. These links could of course appear on a landing page but I'm afraid that would bury them. Perhaps we can discuss this with George as well.
