### ISSUE TITLE
@target temp ids in https://github.com/srophe/e-gedsh/blob/master/gedsh-toc-and-idnos.xml

### ISSUE THREAD

**Issue by davidamichelson** [srophe/e-gedsh#19]
@nathangibson There are still a number of temp ids in this file in the abstracts. Do you know if you have a key to them or a revised version?

**Comment by nathangibson** [comment]
This is something I was working on during my research assistantship and did not finish. Temp IDs are for entities that at the time we did not yet have records for. If I encountered the same entity more than once in the abstracts file, I put a ref on it pointing to the xml:id of the first occurrence. (In other words, they are disambiguated within the file and references could be extracted and cited, but the entity would have to be matched or created.) Note that the reason we don’t have a number of the places is that they are references to dioceses rather than cities. 

It looks like I got through entry 561. Do you want me to do something further with this?

**Comment by davidamichelson** [comment]
No thanks, we will leave them empty.

**Comment by davidamichelson** [comment]
Note to self there are 78 of these.

**Comment by dlschwartz** [comment]
@davidamichelson @nathangibson Do we need to do anything with this still? It's very old and I'm guessing it's not an issue that needs to be addressed in order to release eGEDSH. Please close this issue if that's the case. Thanks.

**Comment by nathangibson** [comment]
I don't think we need to do anything here.
