### ISSUE TITLE
cross references article do not appear in alphabetical list online

### ISSUE THREAD

**Issue by upossekel** [srophe/e-gedsh#44]
div of type cross reference does not appear

```<div type="crossreference">
                <head>Abba Isaiah</head>
                <ab type="crossreference">see <ref rend="bold"
                        target="http://gedsh.bethmardutho.org/Isaiah-of-Scetis">Isaiah of
                        Scetis</ref>
                </ab>
            </div>```

**Comment by wsalesky** [comment]
@davidamichelson @dlschwartz We may need to discuss how to handle this display at our next meeting.

**Comment by dlschwartz** [comment]
I'll put it on the agenda for Wednesday

**Comment by wsalesky** [comment]
@davidamichelson Cross references do not have an 
`<idno type="entry">3</idno>`
Which may throw off my sort, and sends all the cross refs to the end of the browse. Can we add an idno/@type='entry'?

**Comment by dlschwartz** [comment]
We could do that. Let's discuss later when we meet. We would have to redo the numbering on all idno/@type='entry' because right now the numbering simply skips the cross references. Since the entries in the print version aren't numbered, I do not think it matters what numbers we use for an idno. But perhaps I'm not thinking of something important.

**Comment by wsalesky** [comment]
Link on the referenced name.
italicize 'see'

**Comment by wsalesky** [comment]
Added italic and bold to drop down browse and main browse. Added link to cross ref title in main browse.
