### ISSUE TITLE
consider omitting 'idem' in bibliography

### ISSUE THREAD

**Issue by upossekel** [srophe/e-gedsh#48]
The use of 'idem' and similar is very much geared toward printed text, and we might want to consider replacing this with the author name.

**Comment by dlschwartz** [comment]
I'll go ahead and add this to the comments in the "User Interface" task in Asana. I think there is good reason to make this change, but this is the kind of thing we will want to discuss with George, et alt. before we make it. Since we can do this automatically, let's simply put this together with a list of issues for the user interface.

**Comment by dlschwartz** [comment]
@upossekel I've removed the idems from the TEI. This will show up in the html on Monday along with some additional edits. Things are coming together.
