### ISSUE TITLE
Marking the Figures

### ISSUE THREAD

**Issue by davidamichelson** [srophe/e-gedsh#8]
@wsalesky and @dlschwartz Could the two of you please work together to mark all the figure references please?

For now, it appears that all mentions of figures are in a separate final tei:p element in each div/@type="entry" with the following regular format:

```
<p>See Fig. 52, 53, 81, 107, 120c, 121, 122c, 123c, and 124.</p>
<p>See Fig. 124.</p>
```

**Comment by davidamichelson** [comment]
Here is the place to look in the TEI: http://www.tei-c.org/release/doc/tei-p5-doc/en/html/FT.html#FTGRA

**Comment by davidamichelson** [comment]
As an FYI, we do need to assign URIs to the figures and there is metadata we should pull from the indesign files about them. There is also the captions from intext, which would also need to be pulled from indesign.

**Comment by davidamichelson** [comment]
Page xxxvii of Gedsh for page numbers

**Comment by nathangibson** [comment]
Per 10/4/16 meeting Figure format should be http://gedsh.bethmardutho.org/fig/1, correct @dlschwartz

**Comment by dlschwartz** [comment]
@davidamichelson A quick clarification on URIs for figs. Is there a problem in assigning http://gedsh.bethmardutho.org/fig/71c to the figure labeled Fig. 71c in the back matter? This seems fine to me since the system of figure numbers used in GEDSH already employs URIs. All I need to do is add the web address portion. Just want to make sure I'm not missing something. Thanks.

**Comment by dlschwartz** [comment]
It's done.
