### ISSUE TITLE
editorial changes to Addai do not display 

### ISSUE THREAD

**Issue by upossekel** [srophe/e-gedsh#81]
In the entry on Addai, various changes were made that don't display. E.g.,  the word 'Teaching' is italicized but it is not in the print version. My changes to the XML (twice towards end of 2nd paragraph and once at end of 3rd paragraph. Code lines 3721 and 3737) don't display online. There were other changes, too. A problem with the 'hook'?

http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/entry.html?id=http://gedsh.bethmardutho.org/Addai-Teaching-of&num=19

Perhaps this would be remedied if the most recent XML version were uploaded?

Many thanks!
Ute

**Comment by wsalesky** [comment]
@upossekel the italics are in the latest version of the data (I just checked). Perhaps your changes have not been merged in yet?

**Comment by upossekel** [comment]
Dear Winona and David,

 

Thanks Winona for taking a look. These changes are certainly in my version – David and Dan decided for me to work off the master branch – and I thought I had uploaded them. Perhaps I made a mistake? David, could you please look into this?

 

I last worked on this on 2 December and committed changes. Did I forget to pull request? If so, how do I do it now? Github tells me there are no changes currently.

 

David, I have to go out now and will be back by 4.30pm EST. Are you available for a brief skype session then?

 

Thanks for your help,

Ute

**Comment by davidamichelson** [comment]
Hi @wsalesky and @upossekel 

@wsalesky I think you may need to pull the latest version of the data. At line 3721 the current version of Master branch has no italics, yet the HTML is still showing italics for the word "Teaching" in this phrase:

```and the early 5th-cent. Teaching remains somewhat unclear, and several expansions of the Teaching obviously belong to the 4th and 5th <abbr>cent.</abbr></p>```

@upossekel I think you have done everything correctly here! Just an upload issue so no need to meet. Also FYI, since these issues are public on the web, I would recommend not to post any personal information (eg times we can meet).

-Dave

**Comment by wsalesky** [comment]
Okay, sorry about the delay, the latest version should be up. Do you see it?
